name: Update Public Holidays Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  update_holidays:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true  # Forces Node20 for testing
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true  # Optional: Allow using Node16 if necessary until full transition to Node20

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies (if any)
      run: |
        # Add your install dependencies here if you need any npm packages
        # npm install

    - name: Fetch Public Holidays Data for Madagascar
      run: |
        curl -o public_holidays.json https://date.nager.at/api/v3/publicholidays/$(date +%Y)/MG

    - name: Commit and push the changes
      run: |
        git config --global user.name "Ezdev2"
        git config --global user.email "fansoaezra@gmail.com"
        git add public_holidays.json
        git commit -m "Update public holidays data for Madagascar" || echo "No changes to commit"
        it push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Ezdev2/public-holiday-check.git
